version: '3.9'

services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - food_network
      - nginx_certs:/etc/ssl/certs
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 1025:1025
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - ./:/code
    networks:
      - food_network
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - food_network

networks:
  food_network:
    external: True
    driver: bridge
  nginx_certs:
    external: true