# Generated by Django 4.2.11 on 2024-06-16 06:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(max_length=100)),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('building_num', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('apartment_number', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'address',
                'db_table': '"food"."address"',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('address', models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, to='food_free_app.address')),
            ],
            options={
                'verbose_name': 'shop',
                'db_table': '"food"."shop"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('role', models.TextField(choices=[('USER', 'USER'), ('OPERATOR', 'OPERATOR'), ('ADMIN', 'ADMIN')], default='USER')),
                ('address', models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, to='food_free_app.address')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': '"food"."user"',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.shop')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.user')),
            ],
            options={
                'verbose_name': 'subscription',
                'db_table': '"food"."subscription"',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.TextField()),
                ('is_hot', models.BooleanField()),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.shop')),
            ],
            options={
                'verbose_name': 'product',
                'db_table': '"food"."product"',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.TextField(choices=[('CREATED', 'CREATED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='CREATED')),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.shop')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.user')),
            ],
            options={
                'verbose_name': 'mailingmessage',
                'db_table': '"food"."mailingmessage"',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.shop')),
            ],
            options={
                'verbose_name': 'mailinglist',
                'db_table': '"food"."mailinglist"',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.shop')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='food_free_app.user')),
            ],
            options={
                'verbose_name': 'feedback',
                'db_table': '"food"."feedback"',
            },
        ),
    ]
