version: '3.9'

services:
  bot:
    container_name: bot
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 1026:1026
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - ./:/code
    networks:
      - food_network

networks:
  food_network:
    external: True